#бот
BOT_TOKEN = "BOT_TOKEN"

#Чаты
ADMIN_ID = "ADMIN_ID"
QUESTION_ID = "QUESTION_ID"
IDEA_ID = "IDEA_ID"

#БД
DB_NAME = 'DB_NAME'
DB_USER = 'DB_USER'
DB_PASSWORD = 'DB_PASSWORD'
DB_HOST = 'DB_HOST'

#e-mails
EMAIL_SENDER = 'EMAIL_SENDER'
EMAIL_PASSWORD = 'EMAIL_PASSWORD'

MEDICAL_MAIL = 'MEDICAL_MAIL'
LEGAL_MAIL = 'LEGAL_MAIL'
PSYCHOLOGICAL_MAIL = 'PSYCHOLOGICAL_MAIL'
FINANCIAL_MAIL = 'FINANCIAL_MAIL'
DIFFICULT_SITUATION_MAIL = 'DIFFICULT_SITUATION_MAIL'
OTHER_QUESTIONS_MAIL = 'OTHER_QUESTIONS_MAIL'